### ISSUE TITLE
A05 section 2010 is missing data

### ISSUE THREAD

**Issue by ocean-matt** [kkats/GO-SHIP-Easy-Ocean#12]
Hello, 

I am currently using GO-SHIP EasyOcean at the A05 section, across all available years. I have noticed the following bug:
2010 is missing data that is available in the 'raw' netcdf files downloaded from the CCHDO database. Please see the plot below:
![image](https://github.com/kkats/GO-SHIP-Easy-Ocean/assets/45100819/8d9962c9-4d49-4562-aed6-25c362bd47b7)

**Comment by kkats** [comment]
This is not a bug. The stations occupied in 2010 were quite different from the other years in the middle part of the section, and hence not included in the gridded product.
![image](https://github.com/kkats/GO-SHIP-Easy-Ocean/assets/11055789/4c77a558-9932-4d7f-8e26-6e6be50719a4)

And now I noticed that the stations 2020 were also quite different but included in the gridded product. I deliberately leave this issue open so that I will fix this problem in next year's update. Thank you for your comment.
